### ISSUE TITLE
Build出错

### ISSUE THREAD

**Issue by mikumifa** [zhaoolee/WordPressXMLRPCTools#12]
```
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    wp = Client(xmlrpc_php, username, password)
  File "/home/runner/.local/share/virtualenvs/wordPress-ZFnKpXjJ/lib/python3.8/site-packages/wordpress_xmlrpc/base.py", line 24, in __init__
    self.supported_methods = self.server.mt.supportedMethods()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 110[9](https://github.com/mikumifa/wordPress/actions/runs/3351390519/jobs/5552808332#step:6:10), in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line [10](https://github.com/mikumifa/wordPress/actions/runs/3351390519/jobs/5552808332#step:6:11)[11](https://github.com/mikumifa/wordPress/actions/runs/3351390519/jobs/5552808332#step:6:12), in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line [13](https://github.com/mikumifa/wordPress/actions/runs/3351390519/jobs/5552808332#step:6:14)09, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
Error: Process completed with exit code 1.
```

这种出错该怎么解决

**Comment by zhaoolee** [comment]
目录结构有问题，按照fork过来的目录来

mikumifa ***@***.***> 于2022年10月29日周六 20:37写道：

**Comment by siyuanzhou** [comment]
您好，我遇到同样的问题，目录结构就是直接fork过来，一点没改呀，谢谢您啦
